version: "3"
services:
#zookeper-service
  zookeeper01:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    volumes:
      - './data/zoo01:/bitnami/zookeeper'

    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=zookeeper01:2888:3888;zookeeper02:2888:3888
    container_name: zookeeper01

  zookeeper02:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2182:2181'
    volumes:
      - './data/zoo02:/bitnami/zookeeper'

    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zookeeper01:2888:3888;zookeeper02:2888:3888
    container_name: zookeeper02

#kafka-broker-service

  broker01:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
      - '29092:29092'
    volumes:
     - ./data/kafka01:/bitnami/kafka

    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29092,EXTERNAL://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker01:29092,EXTERNAL://localhost:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181,zookeeper02:2181
      - KAFKA_BROKER_ID=1
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    container_name: broker01
    depends_on:
      - zookeeper01
      - zookeeper02

  broker02:
    image: 'bitnami/kafka:latest'
    ports:
      - '9093:9093'
      - '29093:29093'
    volumes:
      - ./data/kafka02:/bitnami/kafka

    environment:
      - KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP=INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      - KAFKA_CFG_LISTENERS=INTERNAL://:29093,EXTERNAL://:9093
      - KAFKA_CFG_ADVERTISED_LISTENERS=INTERNAL://broker02:29093,EXTERNAL://localhost:9093
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper01:2181,zookeeper02:2181
      - KAFKA_BROKER_ID=2
      - KAFKA_INTER_BROKER_LISTENER_NAME=INTERNAL
      - ALLOW_PLAINTEXT_LISTENER=yes
    container_name: broker02
    depends_on:
      - zookeeper01
      - zookeeper02
